version: '3'

services:
#  service:
#    image: 'tg-bot-courier:latest'
#    restart: always
#    build: ./tgbot
#    volumes:
#      - ./tgbot:/app
#    container_name: service
#    ports:
#      - "8082:8082"
#    depends_on:
#      - db
#      - rabbitmq
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/database
#      - SPRING_DATASOURCE_USERNAME=admin
#      - SPRING_DATASOURCE_PASSWORD=admin
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
#  dispatcher:
#    image: 'dispatcher-courier-bot:latest'
#    restart: always
#    build: ./dispatcher
#    volumes:
#      - ./dispatcher:/app
#    container_name: dispatcher
#    ports:
#      - "8081:8081"
#    depends_on:
#      - rabbitmq
#  flyway:
#    image: flyway/flyway
#    command: -url=jdbc:postgresql://db:5432/database -schemas=public -user=admin -password=admin migrate
#    volumes:
#      - ./migration:/flyway/sql
#    depends_on:
#      - db
#  db:
#    image: 'postgres:16'
#    container_name: db
#    environment:
#      - POSTGRES_USER=admin
#      - POSTGRES_PASSWORD=admin
#      - POSTGRES_DB=database
  rabbitmq:
    image: rabbitmq:3.11.0-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 20s
      retries: 5
#  redis:
#    container_name: redis
#    hostname: redis
#    image: redis:3.2
#    restart: always
#    #    entrypoint: redis-server --appendonly yes --requirepass $REDIS_PASSWORD --maxmemory 512mb --maxmemory-policy allkeys-lru
#    ports:
#      - "6379:6379"
#    environment:
#      - REDIS_PASSWORD=my-password
#      - REDIS_DATABASES=16



